// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZqZY9Xgtdn3g9JLiAdTnBXuTSjgX69Bw',
    appId: '1:893439458788:web:dbc1aefe9cb77f21c59bf1',
    messagingSenderId: '893439458788',
    projectId: 'flutterdayseven',
    authDomain: 'flutterdayseven.firebaseapp.com',
    storageBucket: 'flutterdayseven.firebasestorage.app',
    measurementId: 'G-EF89ETV7TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchhwGpkMIojeuTcePMmPYOAPoA8Op030',
    appId: '1:893439458788:android:0d100cefbafa32edc59bf1',
    messagingSenderId: '893439458788',
    projectId: 'flutterdayseven',
    storageBucket: 'flutterdayseven.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZqZY9Xgtdn3g9JLiAdTnBXuTSjgX69Bw',
    appId: '1:893439458788:web:a1d5be80232038adc59bf1',
    messagingSenderId: '893439458788',
    projectId: 'flutterdayseven',
    authDomain: 'flutterdayseven.firebaseapp.com',
    storageBucket: 'flutterdayseven.firebasestorage.app',
    measurementId: 'G-0WG72J2QVZ',
  );
}
